// Offline generator for the HiFloat4 decode table + encoding boundaries
// (golden values sourced from op::HiFloat4 in libnnopbase.so from the CANN toolkit).
// dlopen(RTLD_LAZY): the codec is pure bit-manipulation; lazy binding avoids triggering
// libnnopbase's driver dependencies (same approach used for HiF8/fp4).
//   FloatToHiFloat4(float)->HiFloat4{uint8_t}, HiFloat4ToFloat(HiFloat4)->float,
//   HiFloat4 is a single-byte struct.
#include <cstdio>
#include <cstdlib>
#include <cstdint>
#include <cstring>
#include <dlfcn.h>

typedef uint8_t (*Enc)(float);    // FloatToHiFloat4
typedef float   (*Dec)(uint8_t);  // HiFloat4ToFloat

int main() {
    const char *path = getenv("CANN_NNOPBASE") ? getenv("CANN_NNOPBASE") : "libnnopbase.so";
    void *h = dlopen(path, RTLD_LAZY | RTLD_LOCAL);
    if (!h) { fprintf(stderr, "dlopen fail: %s\n", dlerror()); return 1; }
    Enc enc = (Enc)dlsym(h, "_ZN2op8HiFloat415FloatToHiFloat4Ef");
    Dec dec = (Dec)dlsym(h, "_ZN2op8HiFloat415HiFloat4ToFloatES0_");
    if (!enc || !dec) { fprintf(stderr, "dlsym fail\n"); return 1; }

    // HiFloat4 decode table (fp32 bit patterns), generated from libnnopbase op::HiFloat4
    printf("// HiFloat4 decode table (fp32 bits), generated by libnnopbase op::HiFloat4\n");
    printf("static __device__ __constant__ uint32_t HIF4_DEC[16] = {\n   ");
    for (int c = 0; c < 16; c++) {
        float f = dec((uint8_t)c); uint32_t u; std::memcpy(&u, &f, 4);
        printf(" 0x%08xu,", u);
        if (c == 7) printf("\n   ");
    }
    printf("\n};\n");

    // Encoding magnitude-code boundaries: minimum |x| that maps to magnitude code c (1..7)
    printf("static __device__ __constant__ float HIF4_B[8] = {0");
    int target = 1;
    for (double x = 0; x <= 3.0 && target < 8; x += 1e-6) {
        int mag = enc((float)x) & 0x7;
        if (mag >= target) { printf(",%.9gf", x); target = mag + 1; }
    }
    printf("};\n");
    dlclose(h);
    return 0;
}
